### PR TITLE
Revamped inventories conversion

### PR DESCRIPTION
**Pull request by FireRainV**
The dark inventory is no longer attached to the ball of junk, it's now a variable.
The light inventory is no longer a storage in the dark inventory, it's now a variable.

### CODE REVIEW

**Comment by NyakoFox** [comment]
There's a conflict. Other than that, I'll let @SylviBlossom review this.

**Comment by FireRainV** [comment]
fixed that @MrOinky and fixed the conflict.

**Comment by NyakoFox** [comment]
There's conflicts, and also will this break old save files?

**Comment by MrOinky** [comment]
> > There's conflicts, and also will this break old save files?
> 
> It doesn't say that it has a conflict to me. 

The conflict you can't see is likely happening because you fixed the original conflicts via a merge commit instead of a rebase, you can fix it by rebasing on the latest commit of `upstream/main` instead (this will cause the merge commit to disappear, you will probably need to fix the conflict again as part of the rebase)

**Comment by FireRainV** [comment]
> > > There's conflicts, and also will this break old save files?
> > 
> > 
> > It doesn't say that it has a conflict to me.
> 
> The conflict you can't see is likely happening because you fixed the original conflicts via a merge commit instead of a rebase, you can fix it by rebasing on the latest commit of `upstream/main` instead (this will cause the merge commit to disappear, you will probably need to fix the conflict again as part of the rebase)

like this?

**Pull request merged**
