### PR TITLE
Added all the missing key items

### PR DESCRIPTION
**Pull request by FireRainV**
Includes: BrokenCake, Lancer, Rouxls Kaard and Starwalker.

### CODE REVIEW

**Comment by NyakoFox** [comment]
They were left out for a reason, or at least most were -- I don't remember why we left out BrokenCake. Anyway, how was Lancer ported? Doesn't he change according to plot values, and route? Is this customizable?

**Comment by FireRainV** [comment]
For description text, you can just override Item:getDescription().
As for animation, I just made it that you can choose the animation by setting the LancerGotchi.movecon to a value above 10.
11 is stone, 12 is instant sleeping.

**Comment by FireRainV** [comment]
Here's an example:

image

**Comment by FireRainV** [comment]
Just made it even easier to choose an animation:
item:getCustomLancerAnimation() return <animation>

**Pull request closed without merging**
