### PR TITLE
cutscene + transition = softlock | fixed!

### PR DESCRIPTION
**Pull request by FireRainV**

### CODE REVIEW

**Comment by NyakoFox** [comment]
IIRC this is supposed to be so you can have cross-map cutscenes.

**Comment by FireRainV** [comment]
The cutscene won't even play though when transitioning, it will simply softlock you.
It would be smarter to start a new cutscene after going to the next map.

**Comment by AcousticJammYT** [comment]
Not true; I have cross-map cutscenes and they work well in Kristal.

**Comment by FireRainV** [comment]
So what do I do? Should I close this PR?

**Comment by AcousticJammYT** [comment]
Yeah, that probably seems like the best option

**Comment by FireRainV** [comment]
ok

**Pull request closed without merging**
