### PR TITLE
Documentation for `Arena`, `ArenaMask`, `ArenaSprite`, `Encounter`, `Solid`, `Soul`, `GrazeSprite`, `Battler`, `EnemyBattler`, `PartyBattler`, `Recruit`, `Wave`, `SnowGraveSpell` 

### PR DESCRIPTION
**Pull request by MrOinky**
Documents all of the above files - also makes one code change because some Encounter callbacks were being passed nil values where they shouldn't have been in `battle.lua`

### CODE REVIEW

**Comment by MrOinky** [comment]
Marked as a draft while i finish up documenting the last few files on the list

**Comment by MrOinky** [comment]
docs for all these are done, marked as ready for review!

**Comment by NyakoFox** [comment]
There's conflicts, can you rebase?

**Comment by MrOinky** [comment]
Rebased the branch, should be all fixed now!

**Comment by NyakoFox** [comment]
lets go gambling

**Pull request merged**
